#!/bin/bash
# setup_cron.sh - 在服务器上一键配置三个项目的 cron 定时任务
#
# 使用方法：
#   bash deploy/setup_cron.sh /path/to/projects
#
# 参数：
#   PROJECT_BASE  三个项目所在的父目录，默认为脚本所在位置的上两级
#
# 示例：
#   bash deploy/setup_cron.sh ~/ai-news

set -e

PROJECT_BASE="${1:-$(cd "$(dirname "$0")/../.." && pwd)}"
BUZZ_DIR="$PROJECT_BASE/ai-hourly-buzz-server"
REPORT_DIR="$PROJECT_BASE/ai-daily-report-server"
COLUMN_DIR="$PROJECT_BASE/ai-deep-column-server"
LOG_DIR="$PROJECT_BASE/logs"

echo "=== AI News Server 部署 ==="
echo "项目目录: $PROJECT_BASE"
echo ""

# 检查目录
for dir in "$BUZZ_DIR" "$REPORT_DIR" "$COLUMN_DIR"; do
    if [ ! -d "$dir" ]; then
        echo "错误: 目录不存在: $dir"
        exit 1
    fi
done

mkdir -p "$LOG_DIR"

# 检查 Python
PYTHON=$(command -v python3 || command -v python)
if [ -z "$PYTHON" ]; then
    echo "错误: 未找到 Python，请先安装 python3"
    exit 1
fi
echo "Python: $PYTHON ($($PYTHON --version))"

# 安装依赖
echo ""
echo "=== 安装依赖 ==="
$PYTHON -m pip install -r "$BUZZ_DIR/requirements.txt" -q
$PYTHON -m pip install -r "$REPORT_DIR/requirements.txt" -q
$PYTHON -m pip install -r "$COLUMN_DIR/requirements.txt" -q
echo "依赖安装完成"

# 检查 .env 文件
echo ""
echo "=== 检查配置 ==="
for dir in "$BUZZ_DIR" "$REPORT_DIR"; do
    if [ ! -f "$dir/.env" ]; then
        echo "警告: $dir/.env 不存在，请参考 README 创建"
    else
        echo "✓ $dir/.env"
    fi
done

# 写入 cron 任务
echo ""
echo "=== 配置 cron ==="

# 读取现有 crontab（去掉旧的 ai-news 相关行）
EXISTING=$(crontab -l 2>/dev/null | grep -v "ai-news\|ai-hourly-buzz\|ai-daily-report\|ai-deep-column" || true)

# 环境变量加载：从 buzz 的 .env 读取
ENV_LOADER="set -a; source $BUZZ_DIR/.env 2>/dev/null; set +a;"

NEW_CRON="$EXISTING

# === AI News Server (auto-generated by setup_cron.sh) ===
# ai-hourly-buzz: 每小时整点运行
0 * * * * $ENV_LOADER cd $BUZZ_DIR && $PYTHON scripts/main.py --output-dir data >> $LOG_DIR/buzz.log 2>&1

# ai-daily-report: 每天北京时间 7:00 (UTC 23:00 前一天)
0 23 * * * $ENV_LOADER SHARED_DATA_DIR=$BUZZ_DIR/data cd $REPORT_DIR/scripts && $PYTHON main.py >> $LOG_DIR/daily-report.log 2>&1
"

echo "$NEW_CRON" | crontab -

echo "cron 任务已写入："
echo "  - ai-hourly-buzz:   每小时整点"
echo "  - ai-daily-report:  每天 UTC 23:00（北京时间 7:00）"
echo ""
echo "日志目录: $LOG_DIR"
echo ""
echo "=== 部署完成 ==="
echo ""
echo "下一步："
echo "  1. 确认 $BUZZ_DIR/.env 中的密钥已配置"
echo "  2. 手动运行一次测试："
echo "     cd $BUZZ_DIR && $PYTHON scripts/main.py --output-dir data --no-push"
echo "  3. 查看日志："
echo "     tail -f $LOG_DIR/buzz.log"
